# Social networks and the decision to insure

## 1. 패키지 설치

In [8]:
!pip install causalinference numpy scipy causaldata black

Requirement already satisfied: causalinference in /opt/conda/lib/python3.10/site-packages (0.1.3)
Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (1.24.3)
Requirement already satisfied: scipy in /opt/conda/lib/python3.10/site-packages (1.10.1)
Collecting causaldata
  Downloading causaldata-0.1.3.tar.gz (2.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 4.5 MB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py) ... done
Collecting statsmodels (from causaldata)
  Downloading statsmodels-0.14.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 8.4 MB/s eta 0:00:0000:010:01
Collecting pandas (from causaldata)
  Downloading pandas-2.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 3.7 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas->causaldata) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas->causaldata) (2023.3)
Collecting tzdata>=2022.1 (from pandas->causaldata)
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 4.7 MB/s eta 0:00:0000:0100:01
Collecting patsy>=0.5.2 (from statsmodels->causaldata)
  Downloading patsy-0.5.3-py2.py3-none-any.whl (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.8/233.8 kB 4.3 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: packaging>=21.3 in /opt/conda/lib/python3.10/site-packages (from statsmodels->causaldata) (23.1)
Requirement already satisfied: six in /opt/conda/lib/python3.10/site-packages (from patsy>=0.5.2->statsmodels->causaldata) (1.16.0)
Building wheels for collected packages: causaldata
  Building wheel for causaldata (setup.py) ... done
  Created wheel for causaldata: filename=causaldata-0.1.3-py3-none-any.whl size=2645603 sha256=4399cdea6c35b2e27a107bd0caa5913cee8e59f839b26ce229181c62a561fd24
  Stored in directory: /home/jovyan/.cache/pip/wheels/4a/8f/9f/13d3a7ab29b8a8c68f3e5dcc0fe00d0e8eef62fc508a20c7c6
Successfully built causaldata
Installing collected packages: tzdata, patsy, pandas, statsmodels, causaldata
Successfully installed causaldata-0.1.3 pandas-2.0.1 patsy-0.5.3 statsmodels-0.14.0 tzdata-2023.3

In [19]:
!pip install --upgrade statsmodels

Requirement already satisfied: statsmodels in /opt/conda/lib/python3.10/site-packages (0.14.0)
Requirement already satisfied: numpy>=1.18 in /opt/conda/lib/python3.10/site-packages (from statsmodels) (1.24.3)
Requirement already satisfied: scipy!=1.9.2,>=1.4 in /opt/conda/lib/python3.10/site-packages (from statsmodels) (1.10.1)
Requirement already satisfied: pandas>=1.0 in /opt/conda/lib/python3.10/site-packages (from statsmodels) (2.0.1)
Requirement already satisfied: patsy>=0.5.2 in /opt/conda/lib/python3.10/site-packages (from statsmodels) (0.5.3)
Requirement already satisfied: packaging>=21.3 in /opt/conda/lib/python3.10/site-packages (from statsmodels) (23.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas>=1.0->statsmodels) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas>=1.0->statsmodels) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas>=1.0->statsmodels) (2023.3)
Requirement already satisfied: six in /opt/conda/lib/python3.10/site-packages (from patsy>=0.5.2->statsmodels) (1.16.0)

In [50]:
import causaldata
help(causaldata)
dataset = causaldata.social_insure.load_pandas()

Help on package causaldata:

NAME
    causaldata

PACKAGE CONTENTS
    Mroz (package)
    abortion (package)
    adult_services (package)
    auto (package)
    avocado (package)
    black_politicians (package)
    castle (package)
    close_college (package)
    close_elections_lmb (package)
    cps_mixtape (package)
    credit_cards (package)
    gapminder (package)
    google_stock (package)
    gov_transfers (package)
    gov_transfers_density (package)
    greek_data (package)
    mortgages (package)
    nhefs (package)
    nhefs_codebook (package)
    nhefs_complete (package)
    nsw_mixtape (package)
    organ_donations (package)
    restaurant_inspections (package)
    ri (package)
    scorecard (package)
    snow (package)
    social_insure (package)
    texas (package)
    thornton_hiv (package)
    titanic (package)
    training_bias_reduction (package)
    training_example (package)
    yule (package)

DATA
    __all__ = ['auto', 'black_politicians', 'gapminder', 'google_stock', '...

FILE
    /opt/conda/lib/python3.10/site-packages/causaldata/__init__.py

## 2. Understand the data

In [74]:
# 결측치가 없는 데이터
df_without_na = origin_df.dropna()

# 결측치가 있는 데이터
df_with_na = origin_df[origin_df.isna().any(axis=1)]

display(
    "df_without_na", df_without_na.describe(),
    "df_with_na", df_with_na.describe(),
    "origin", origin_df.describe()
)

'df_without_na'

,takeup_survey,age,agpop,ricearea_2010,disaster_prob,male,default,intensive,risk_averse,literacy,pre_takeup_rate
count,1378.000000,1378.000000,1378.000000,1378.000000,1378.000000,1378.000000,1378.000000,1378.000000,1378.000000,1378.000000,1378.000000
mean,0.460813,51.410015,4.891872,13.488549,33.057765,0.902032,0.482583,0.487663,0.174456,0.793904,0.429470
std,0.498643,12.079239,2.073257,22.035801,16.631186,0.297379,0.499878,0.500029,0.306005,0.404647,0.241123
min,0.000000,18.000000,1.000000,0.400000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,42.000000,4.000000,5.000000,20.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.222222
50%,0.000000,50.000000,5.000000,10.000000,30.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.421053
75%,1.000000,60.000000,6.000000,16.000000,50.000000,1.000000,1.000000,1.000000,0.200000,1.000000,0.569196
max,1.000000,85.000000,19.000000,650.000000,100.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

'df_with_na'

,takeup_survey,age,agpop,ricearea_2010,disaster_prob,male,default,intensive,risk_averse,literacy,pre_takeup_rate
count,32.000000,28.000000,26.000000,23.000000,32.000000,29.000000,32.000000,32.000000,32.000000,11.000000,32.000000
mean,0.593750,54.964286,5.384615,9.886957,35.000000,0.931034,0.562500,0.656250,0.225000,0.727273,0.395843
std,0.498991,15.007362,2.228487,6.947747,13.678332,0.257881,0.504016,0.482559,0.320282,0.467099,0.245623
min,0.000000,33.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,40.750000,4.000000,5.000000,20.000000,1.000000,0.000000,0.000000,0.000000,0.500000,0.154135
50%,1.000000,54.500000,5.000000,10.000000,40.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.387500
75%,1.000000,67.000000,6.000000,14.000000,50.000000,1.000000,1.000000,1.000000,0.450000,1.000000,0.566667
max,1.000000,86.000000,12.000000,30.000000,50.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

'origin'

,takeup_survey,age,agpop,ricearea_2010,disaster_prob,male,default,intensive,risk_averse,literacy,pre_takeup_rate
count,1410.000000,1406.000000,1404.000000,1401.000000,1410.000000,1407.000000,1410.000000,1410.000000,1410.000000,1389.000000,1410.000000
mean,0.463830,51.480797,4.900997,13.429422,33.101844,0.902630,0.484397,0.491489,0.175603,0.793377,0.428707
std,0.498867,12.148048,2.076450,21.876182,16.568483,0.296567,0.499934,0.500105,0.306310,0.405029,0.241189
min,0.000000,18.000000,1.000000,0.400000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,42.000000,4.000000,5.000000,20.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.222222
50%,0.000000,51.000000,5.000000,10.000000,30.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.421053
75%,1.000000,60.000000,6.000000,16.000000,50.000000,1.000000,1.000000,1.000000,0.200000,1.000000,0.569196
max,1.000000,86.000000,19.000000,650.000000,100.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [69]:
import pandas as pd

origin_df = pd.DataFrame(dataset.data)

col_describe = {
    "address"         : "Natural village",
    "village"         : "Administrative village",
    "takeup_survey"   : "Whether farmer ended up purchasing insurance. (1 = yes)",
    "age"             : "Household Characteristics - Age",
    "agpop"           : "Household Characteristics - Household Size",
    "ricearea_2010"   : "Area of Rice Production",
    "disaster_prob"   : "Perceived Probability of Disasters Next Year",
    "male"            : "Gender of Household Head (1 = male)",
    "default"         : '"Default option" in experimental format assigned to. (1 = default is to buy, 0 = default is to not buy)',
    "intensive"       : 'Whether or not was assigned to "intensive" experimental session (1 = yes)',
    "risk_averse"     : "Risk aversion measurement",
    "literacy"        : "1 = literate, 0 = illiterate",
    "pre_takeup_rate" : "Takeup rate prior to experiment"
}

for key, val in col_describe.items():
    print(f"{key} - {val}\n")

display(
    origin_df.head(10),
    
    origin_df.describe(),
    
    origin_df.dtypes,
)

address - Natural village

village - Administrative village

takeup_survey - Whether farmer ended up purchasing insurance. (1 = yes)

age - Household Characteristics - Age

agpop - Household Characteristics - Household Size

ricearea_2010 - Area of Rice Production

disaster_prob - Perceived Probability of Disasters Next Year

male - Gender of Household Head (1 = male)

default - "Default option" in experimental format assigned to. (1 = default is to buy, 0 = default is to not buy)

intensive - Whether or not was assigned to "intensive" experimental session (1 = yes)

risk_averse - Risk aversion measurement

literacy - 1 = literate, 0 = illiterate

pre_takeup_rate - Takeup rate prior to experiment

,address,village,takeup_survey,age,agpop,ricearea_2010,disaster_prob,male,default,intensive,risk_averse,literacy,pre_takeup_rate
0,beilian2,beilian,0,62.0,2.0,10.0,30.0,1.0,1,0,0.0,0.0,0.071429
1,beilian2,beilian,1,63.0,5.0,15.0,100.0,1.0,1,0,0.0,1.0,0.071429
2,beilian2,beilian,1,44.0,3.0,7.5,20.0,1.0,1,1,0.0,1.0,0.071429
3,beilian2,beilian,1,76.0,6.0,NaN,50.0,1.0,1,1,0.6,1.0,0.071429
4,beilian2,beilian,0,52.0,6.0,11.0,0.0,1.0,1,1,0.2,1.0,0.071429
5,beilian2,beilian,1,53.0,5.0,35.0,0.0,1.0,1,0,0.0,1.0,0.071429
6,beilian2,beilian,0,72.0,10.0,2.0,40.0,1.0,1,0,0.0,1.0,0.071429
7,beilian2,beilian,1,43.0,6.0,19.0,20.0,1.0,1,0,0.0,1.0,0.071429
8,beilian2,beilian,1,78.0,7.0,14.0,30.0,1.0,1,1,0.4,1.0,0.071429
9,beilian4,beilian,1,73.0,2.0,5.0,50.0,1.0,0,0,0.0,1.0,0.400000

,takeup_survey,age,agpop,ricearea_2010,disaster_prob,male,default,intensive,risk_averse,literacy,pre_takeup_rate
count,1410.000000,1406.000000,1404.000000,1401.000000,1410.000000,1407.000000,1410.000000,1410.000000,1410.000000,1389.000000,1410.000000
mean,0.463830,51.480797,4.900997,13.429422,33.101844,0.902630,0.484397,0.491489,0.175603,0.793377,0.428707
std,0.498867,12.148048,2.076450,21.876182,16.568483,0.296567,0.499934,0.500105,0.306310,0.405029,0.241189
min,0.000000,18.000000,1.000000,0.400000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,42.000000,4.000000,5.000000,20.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.222222
50%,0.000000,51.000000,5.000000,10.000000,30.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.421053
75%,1.000000,60.000000,6.000000,16.000000,50.000000,1.000000,1.000000,1.000000,0.200000,1.000000,0.569196
max,1.000000,86.000000,19.000000,650.000000,100.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

address             object
village             object
takeup_survey        int64
age                float64
agpop              float64
ricearea_2010      float64
disaster_prob      float64
male               float64
default              int64
intensive            int64
risk_averse        float64
literacy           float64
pre_takeup_rate    float64
dtype: object

In [6]:
from causalinference import CausalModel
from causalinference.utils import random_data
#Y is the outcome, D is treatment status, and X is the independent variable
Y, D, X = random_data()
causal = CausalModel(Y, D, X)

In [7]:
print(causal.summary_stats)

Summary Statistics

                      Controls (N_c=2465)        Treated (N_t=2535)
       Variable         Mean         S.d.         Mean         S.d.     Raw-diff
--------------------------------------------------------------------------------
              Y       -0.978        1.729        4.934        2.989        5.912

                      Controls (N_c=2465)        Treated (N_t=2535)
       Variable         Mean         S.d.         Mean         S.d.     Nor-diff
--------------------------------------------------------------------------------
             X0       -0.323        0.946        0.330        0.941        0.692
             X1       -0.347        0.943        0.333        0.943        0.721
             X2       -0.321        0.943        0.312        0.951        0.669

처리 효과 추정: 처리 효과를 추정하는 다양한 방법을 제공합니다. 예를 들어, 이중 차이 추정, 제한화 추정, 역시 추정 등이 있습니다.

기계학습 기반 인과 추론: 기계학습 모델을 사용하여 인과 관계를 추론합니다. 반응 변수와 처리 변수 사이의 인과적 영향을 예측하기 위해 모델을 훈련하고 사용합니다.

부분적 자료 처리: 인과 추론을 위해 자료의 일부만 사용하는 부분적 자료 처리 기법을 제공합니다. 부분적 자료 처리를 통해 개입의 효과를 추정할 수 있습니다.

---

"causalinference"는 인과추론(causal inference)을 위한 Python 라이브러리 중 하나입니다. 이 라이브러리는 인과 관계를 추론하기 위해 다양한 방법을 제공합니다. "causalinference" 라이브러리를 사용하면 인과 관계를 평가하고 인과적 효과를 추정할 수 있습니다.

주요 기능 중 일부는 다음과 같습니다:

1. 처리 효과 추정: 처리 효과를 추정하는 다양한 방법을 제공합니다. 예를 들어, 이중 차이 추정, 제한화 추정, 역시 추정 등이 있습니다.

2. 기계학습 기반 인과 추론: 기계학습 모델을 사용하여 인과 관계를 추론합니다. 반응 변수와 처리 변수 사이의 인과적 영향을 예측하기 위해 모델을 훈련하고 사용합니다.

3. 부분적 자료 처리: 인과 추론을 위해 자료의 일부만 사용하는 부분적 자료 처리 기법을 제공합니다. 부분적 자료 처리를 통해 개입의 효과를 추정할 수 있습니다.

"causalinference" 라이브러리의 사용 방법과 자세한 기능은 해당 라이브러리의 공식 문서를 참조하시기 바랍니다.

---

"causalinference" 라이브러리는 인과 추론을 위한 일반적인 도구로 사용될 수 있습니다. 다양한 사례에서 해당 라이브러리를 사용하여 인과적 효과를 추정하고 인과 관계를 평가할 수 있습니다. 아래는 "causalinference" 라이브러리를 사용한 몇 가지 사례의 예시입니다:

1. 의료 연구: 의료 분야에서는 "causalinference" 라이브러리를 사용하여 특정 치료나 개입이 환자들의 결과에 미치는 인과적 효과를 추정할 수 있습니다. 예를 들어, 특정 약물 치료가 환자의 건강 상태에 어떤 영향을 미치는지를 인과 추론을 통해 파악할 수 있습니다.

2. 교육 정책 평가: 교육 정책의 효과를 평가하기 위해 "causalinference" 라이브러리를 사용할 수 있습니다. 예를 들어, 특정 교육 개입이 학생들의 학업 성취도에 미치는 영향을 추정하여 정책 결정에 도움을 줄 수 있습니다.

3. 사회과학 연구: 사회과학 분야에서는 "causalinference" 라이브러리를 사용하여 사회 현상 간의 원인과 결과 관계를 추론할 수 있습니다. 예를 들어, 정치적 개입이 사회적 변화에 미치는 영향을 인과적으로 이해하기 위해 사용될 수 있습니다.

이는 "causalinference" 라이브러리의 일반적인 사용 사례의 몇 가지 예시일 뿐이며, 인과 추론은 다양한 분야에서 다양한 목적으로 활용될 수 있습니다. 실제 사례에 따라 "causalinference" 라이브러리를 사용하여 인과적 효과를 추정하고 인과 관계를 평가할 수 있습니다.

---

사회과학 연구는 사회 현상과 사회적 현상을 이해하고 분석하기 위해 학문적인 방법과 접근법을 사용하는 학문 분야입니다. 사회과학 연구는 사회학, 정치학, 경제학, 심리학, 국제관계학 등 다양한 하위 분야로 구성됩니다. 이 분야는 사회적 현상의 원인, 결과, 상호작용, 구조, 변화, 행동 등을 이해하고 설명하는 데 관

---

"causalinference" 라이브러리를 활용한 사회과학 연구의 사례를 살펴보겠습니다.

1. 교육 정책 평가: 교육 분야에서 "causalinference"를 사용하여 특정 교육 정책이 학생들의 학업 성취도에 미치는 영향을 평가할 수 있습니다. 예를 들어, 특정 교육 개입(예: 교육 프로그램 도입, 교육 정책 변경)이 학생들의 수학 성적에 미치는 영향을 인과적으로 추정할 수 있습니다. 이를 통해 해당 정책의 효과를 정량화하고 정책 결정에 도움을 줄 수 있습니다.

2. 정치적 개입 평가: 정치학 분야에서 "causalinference"를 활용하여 정치적 개입이 사회적 변화에 미치는 영향을 평가할 수 있습니다. 예를 들어, 특정 정책이 지역 사회의 경제적 성장에 미치는 영향을 인과적으로 추정할 수 있습니다. 이를 통해 정치적 개입의 효과를 분석하고 정책 결정에 대한 이해를 높일 수 있습니다.

3. 사회 복지 프로그램 평가: 사회 복지 분야에서 "causalinference"를 사용하여 특정 사회 복지 프로그램이 개인이나 집단의 복지에 미치는 영향을 평가할 수 있습니다. 예를 들어, 정부의 소득 지원 프로그램이 가정의 경제적 안정성과 사회적 포용성에 미치는 영향을 인과적으로 추정할 수 있습니다. 이를 통해 사회 복지 정책의 효과를 평가하고 개선할 수 있는 방향을 제시할 수 있습니다.

위의 사례는 "causalinference" 라이브러리를 사용하여 사회과학 연구 분야에서 인과 관계를 추론하고 효과를 평가하는 방법을 보여줍니다. 이러한 연구는 정책 결정과 사회적 현상을 이해하고 개선하는 데 도움이 될 수 있습니다.

---

이중 차이 추정, 제한화 추정, 역시 추정은 "causalinference" 라이브러리에서 제공하는 인과 추론 방법 중 일부입니다. 각각의 추정 방법에 대해 자세히 설명해드리겠습니다:

1. 이중 차이 추정 (Double Difference Estimation):
   이중 차이 추정은 개입 그룹과 비개입 그룹 간의 차이를 시간의 흐름에 따라 비교하는 방법입니다. 주로 처리 그룹과 비처리 그룹의 전후 비교를 통해 개입의 효과를 추정하는 데 사용됩니다. 이 방법은 개입 전과 개입 후, 그리고 처리 그룹과 비처리 그룹 사이의 차이를 비교함으로써 개입의 인과적 효과를 추론합니다.

2. 제한화 추정 (Propensity Score Estimation):
   제한화 추정은 처리 그룹과 비처리 그룹 간의 편향을 줄이기 위해 개입 확률을 고려하는 방법입니다. 개입 확률은 개별 개체가 처리 그룹에 속할 확률을 나타내며, 이를 이용하여 개입 그룹과 비개입 그룹 간의 차이를 보정합니다. 제한화 추정은 개입이 발생할 확률에 따라 그룹을 매칭하거나 가중치를 적용하여 인과 추론을 수행합니다.

3. 역시 추정 (Instrumental Variable Estimation):
   역시 추정은 처리 변수와 결과 변수 사이에 독립적인 도구 변수를 사용하여 인과적 효과를 추정하는 방법입니다. 도구 변수는 처리 변수와 결과 변수 간의 연관성을 갖지만 결과 변수에 직접적으로 영향을 미치지 않는 변수입니다. 역시 추정은 처리 변수의 엔도겐성(endogeneity) 문제를 해결하기 위해 사용됩니다. 이 방법은 도구 변수의 독립성을 활용하여 처리 변수의 영향을 추정하고 결과 변수에 대한 인과적 효과를 분리합니다.

위의 추정 방법들은 "causalinference" 라이브러리에서 제공되는 일부 인과 추론 기법입니다. 각각의 방법은 다른 상황에서 사용되며, 연구의 목적과 데이터의 특성에 따라 선택됩니다. 이러한 방법들은 개입의 인과적 효과를 추정하고 편향을 보정하여 더 신뢰할 수 있는 결과를 도출하는 데 도움을 줍니다.

---

처리 효과 추정과 기계학습 기반 인과 추론은 "causalinference" 라이브러리에서 제공하는 두 가지 다른 방법론입니다. 이들의 주요 차이점을 설명해드리겠습니다:

1. 처리 효과 추정 (Treatment Effect Estimation):
   처리 효과 추정은 개입(처리)의 인과적 효과를 추정하는 데 중점을 둡니다. 이 방법은 개입을 받은 그룹과 비개입 그룹 간의 차이를 분석하여 개입의 효과를 측정합니다. 주로 이중 차이 추정 및 제한화 추정과 관련된 방법을 사용합니다. 처리 효과 추정은 개입 그룹과 비개입 그룹 사이의 차이를 인과적으로 분석하고, 개입의 효과 크기와 통계적 유의성을 추정합니다.

2. 기계학습 기반 인과 추론 (Machine Learning-Based Causal Inference):
   기계학습 기반 인과 추론은 인과적 효과를 추론하기 위해 기계학습 모델을 활용합니다. 이 방법은 개입 변수와 결과 변수 사이의 복잡한 관계를 모델링하고, 개입의 영향을 예측하는 데 기계학습 알고리즘을 사용합니다. 예를 들어, 회귀 분석, 의사결정 트리, 랜덤 포레스트, 신경망 등 다양한 기계학습 모델을 활용하여 인과 관계를 추론할 수 있습니다.

처리 효과 추정은 처리 그룹과 비처리 그룹의 차이를 통해 개입의 효과를 분석하는 반면, 기계학습 기반 인과 추론은 모델을 사용하여 개입의 효과를 예측하고 추론합니다. 처리 효과 추정은 일반적으로 명시적인 모델 가정을 기반으로 하며, 개입 변수와 결과 변수 간의 관계를 통계적으로 분석합니다. 반면에 기계학습 기반 인과 추론은 모델을 사용하여 더 유연하고 복잡한 관계를 모델링하고 예측합니다. 이를 통해 개입의 효과를 예측하고 변수 간의 복잡한 상호작용을 고려할 수 있습니다.

두 방법은 연구의 목적과 데이터의 특성에 따라 선택되며, 개입의 효과를 추정하고 인과적 효과를 이해하는 데 다

---

부분적 자료 처리(partial data treatment)는 인과 추론에서 사용되는 방법 중 하나입니다. 이 방법은 일부 개체 또는 그룹만이 처리(개입)를 받은 경우에 대한 인과 효과를 추정하는 데 사용됩니다.

보통 인과 추론에서는 처리 그룹과 비처리 그룹 사이의 차이를 분석하여 개입의 효과를 추정합니다. 그러나 모든 개체나 그룹이 처리를 받지 않는 경우 또는 처리를 받은 개체 또는 그룹의 수가 제한적인 경우에는 인과 추론이 어려울 수 있습니다. 이때 부분적 자료 처리는 처리를 받은 개체 또는 그룹 중에서 일부만을 사용하여 인과 효과를 추정하는 방법입니다.

부분적 자료 처리는 제한화 추정, 역시 추정 등과 연계하여 사용될 수 있습니다. 예를 들어, 제한화 추정에서는 개입 확률을 고려하여 처리 그룹과 비처리 그룹을 매칭하거나 가중치를 적용합니다. 이때 처리 그룹 중에서 일부만이 개입을 받은 경우에는 이러한 매칭 또는 가중치 적용에서 해당 개체 또는 그룹만을 고려하여 부분적 자료 처리를 수행할 수 있습니다.

부분적 자료 처리는 실제 상황에서 모든 개체 또는 그룹에 개입을 적용하기 어려운 경우에 유용하게 사용될 수 있습니다. 처리를 받은 개체 또는 그룹의 수가 제한적인 경우에도 인과 효과를 추정할 수 있으며, 연구의 효율성과 실용성을 높일 수 있습니다. 그러나 부분적 자료 처리는 선택 편향이나 외생성 가정 등에 영향을 받을 수 있으므로 신중하게 적용해야 합니다.

---

개체 또는 그룹은 인과 추론에서 사용되는 단위입니다. 이해하기 쉽게 예를 들어 설명하겠습니다.

개체 (Unit):
개체는 인과 추론에서 분석의 대상이 되는 개별적인 단위입니다. 예를 들어, 교육 정책의 효과를 연구한다고 가정해봅시다. 이 경우, 개체는 학생으로 정의될 수 있습니다. 각 학생은 개별적인 개체이며, 개별적인 특성과 결과를 가지고 있습니다. 개체는 보통 독립적으로 측정되고 분석되는 단위입니다.

그룹 (Group):
그룹은 개체들의 집합으로 구성됩니다. 그룹은 개체들을 특정한 특성이나 조건에 따라 구분하여 분석하는데 사용됩니다. 예를 들어, 교육 정책의 효과를 연구한다면, 그룹은 처리 그룹과 비처리 그룹으로 나뉘어질 수 있습니다. 처리 그룹은 특정 교육 개입을 받은 학생들의 집합이고, 비처리 그룹은 해당 개입을 받지 않은 학생들의 집합입니다. 그룹은 일반적으로 개체들을 묶어서 비교하고 인과 효과를 추론하는 데 사용됩니다.

개체와 그룹은 인과 추론에서 중요한 개념으로, 개별적인 개체의 특성과 처리 여부, 그리고 개체를 그룹화하여 처리 그룹과 비처리 그룹을 구분하여 분석합니다. 이를 통해 개체 수준의 효과와 그룹 수준의 효과를 추론할 수 있습니다. 개체와 그룹은 연구의 대상에 따라 다르게 정의될 수 있으며, 연구 질문과 목적에 따라 적절하게 선택되고 사용됩니다.

In [ ]:
## 지울 예정...

# install.packages('tidyverse')
# install.packages('modelsummary')
# install.packages('fixest')
# install.packages('causaldata')
# install.packages('gmm')
# install.packages('GGally')
# install.packages('CBPS')
# install.packages('Rtools')
# install.packages('ggpubr')

# Import library
library(tidyverse); library(modelsummary); library(fixest); library(gmm); library(ggplot2); library(GGally)
library(CBPS); 

# import social insure dataset from causaldata package
d <- causaldata::social_insure

# data set describe
head(d)
summary(d) # 데이터 중 age, agpop 등 5개 컬럼에서 NA 값들이 발견
boxplot(d)

# remove NA cell
d_prep <- d %>%
  na.omit()

## data description (KOR)
# - **address** Natural village: 주소
# - **village** Administrative village: 행정 주소 (전처리)
# - **takeup_survey** Whether farmer ended up purchasing insurance. (1 = yes)
# : 최종적인 농부의 보험 가입 여부
# - **age** Household Characteristics - Age: 가구특성-연령
# - **agpop** Household Characteristics - Household Size: 가구특성-가구 규모
# - **ricearea_2010** Area of Rice Production: 쌀 생산 면적 (농부의 자산, 생산 규모)
# - **disaster_prob** Perceived Probability of Disasters Next Year: 차년도 재해 발생 확률
# - **male** Household Caracteristics: Gender of Household Head (1 = male): 가구주 성별 (1 남성)
# - **default** "Default option" in experimental format assigned to. (1 = default is to buy, 0 = default is to not buy): 실험 양식 할당 번호: 기본값=1은 구매(보험 가입), 0은 미구매
# - **intensive** Whether or not was assigned to "intensive" experimental session (1 = yes)
# : 실험 세션에 할당되었는지 여부
# - **risk_averse** Risk aversion measurement: 위험 회피 성향 점수
# - **literacy** 1 = literate, 0 = illiterate: 문해력, 1=읽고쓸줄 앎, 0=문맹
# - **pre_takeup_rate** Takeup rate prior to experiment: 실험 전 보험 수급율

# 산포도 및 변수간 상관성 시각화
# ggpairs( d %>%
#            select(takeup_survey, male, age, agpop, ricearea_2010,
#                   literacy, intensive, risk_averse, disaster_prob,
#                   pre_takeup_rate, default))

###############################################

# 실험 참여 여부를 -> treatment로 지정
d_prep$treatment<-d_prep$intensive

# treat 0,1 숫자 확인
table(d_prep$treatment)

# 0   1 
# 706 672 

# d_prep$treatment <- as.factor(d_prep$treatment) # 0,1 숫자값을 factor로 변경

#calculate propensity score using logistic regression model
prop_model <-glm(treatment~takeup_survey+male+age+agpop+ricearea_2010+
                 literacy+risk_averse+disaster_prob+
                 village+address+pre_takeup_rate,data=d_prep,family=binomial(link="logit"))

#save predicted scores to dataset
d_prep$pr_score <-predict(prop_model,type="response")

library(ggplot2)
library(ggpubr)
#this plots the distribution of our estimated propensity scores
g<- ggplot(d_prep,aes(x = pr_score, color=as.factor(d_prep$treatment),fill=as.factor(d_prep$treatment))) +
  geom_density(alpha=.47) + 
  xlab("Estimated Probability of Recieving Oral Therapy") +
  ylab ("Density") +theme_minimal()+ theme(
    axis.ticks.y=element_blank(),
    panel.grid.minor=element_blank(),
    legend.title=element_blank(),
    text = element_text(size=16),
    axis.title.x =element_text(hjust = 0.2,size=16))
ggpar(g,palette="nejm")


library(CBPS)
#calculate weights using CBPS package and function
cbpsoral <-CBPS(treatment~takeup_survey+male+age+agpop+ricearea_2010+
                  literacy+risk_averse+disaster_prob+
                  village+address+pre_takeup_rate,data=d_prep,standardize=FALSE,method="exact",ATT=1)

d_prep$cbps <-cbpsoral$weights

#create matched dataset based on same propensity model
#here we switched the outcome, as matchit requires the larger group to be the reference if variable ratio is being used
#We are capturing up to 4 oral therapy matches for every sipuleucel-T subject
matched <- matchit((1-treatment)~takeup_survey+male+age+agpop+ricearea_2010+
                     literacy+risk_averse+disaster_prob+
                     village+address+pre_takeup_rate,data =d_prep, method = "nearest",caliper=.2,ratio=4)

#looked at characteristics of matched object
matched_sum<-summary(matched)
# treat = control 그룹 수가 일치하지 않기에 일부 treat 그룹은 매칭을 받지 못하였다.
# Warning message: Fewer control units than treated units; not all treated units will get a match.